require('pry-byebug')
require_relative('models/customer.rb')
require_relative('models/film.rb')
require_relative('models/ticket.rb')
require_relative('models/screening.rb')

Customer.delete_all()
Film.delete_all()
Ticket.delete_all()
Screening.delete_all()

# ----------------------------------------
customer1 = Customer.new('name' => 'Mari', 'funds' => 50)
customer1.save()
customer2 = Customer.new('name' => 'Dina', 'funds' => 20)
customer2.save()
customer3 = Customer.new('name' => 'Sezen', 'funds' => 40)
customer3.save()
customer4 = Customer.new('name' => 'Irma', 'funds' => 30)
customer4.save()
customer5 = Customer.new('name' => 'Louise', 'funds' => 75)
customer5.save()

# customer3.funds = 200
# customer3.update()
# -----------------------------------------
film1 = Film.new('title' => 'A beautiful mind', 'price' => 9)
film1.save()
film2 = Film.new('title' => 'Good Will Hunting', 'price' => 10)
film2.save()
film3 = Film.new('title' => 'Hidden Figures', 'price' => 7)
film3.save()
film4 = Film.new('title' => 'The Martian', 'price' => 8)
film4.save()
film5 = Film.new('title' => 'Les Miserables', 'price' => 11)
film5.save()
film6 = Film.new('title' => 'The artist', 'price' => 7)
film6.save()
film7 = Film.new('title' => 'Good Will Hunting', 'price' => 8)
film7.save()

# -----------------------------------------
ticket1 = Ticket.new('customer_id' => customer1.id, 'film_id' => film1.id, 'cinema' => 'Edinburgh', 'type' => 'peak')
ticket1.save()
ticket2 = Ticket.new('customer_id' => customer2.id, 'film_id' => film1.id, 'cinema' => 'Edinburgh', 'type' => 'discounted')
ticket2.save()
ticket3 = Ticket.new('customer_id' => customer4.id, 'film_id' => film7.id, 'cinema' => 'Edinburgh', 'type' => 'discounted')
ticket3.save()
ticket4 = Ticket.new('customer_id' => customer1.id, 'film_id' => film5.id, 'cinema' => 'Edinburgh', 'type' => 'full price')
ticket4.save()
ticket5 = Ticket.new('customer_id' => customer1.id, 'film_id' => film7.id, 'cinema' => 'Edinburgh', 'type' => 'full price')
ticket5.save()
ticket6 = Ticket.new('customer_id' => customer4.id, 'film_id' => film5.id, 'cinema' => 'Edinburgh', 'type' => 'peak')
ticket6.save()
ticket7 = Ticket.new('customer_id' => customer5.id, 'film_id' => film1.id, 'cinema' => 'Edinburgh', 'type' => 'full price')
ticket7.save()
ticket8 = Ticket.new('customer_id' => customer5.id, 'film_id' => film2.id, 'cinema' => 'Edinburgh', 'type' => 'full price')
ticket8.save()
ticket9 = Ticket.new('customer_id' => customer5.id, 'film_id' => film3.id, 'cinema' => 'Edinburgh', 'type' => 'full price')
ticket9.save()
ticket10 = Ticket.new('customer_id' => customer5.id, 'film_id' => film4.id, 'cinema' => 'Edinburgh', 'type' => 'full price')
ticket10.save()
ticket11 = Ticket.new('customer_id' => customer5.id, 'film_id' => film5.id, 'cinema' => 'Edinburgh', 'type' => 'discounted')
ticket11.save()
ticket12 = Ticket.new('customer_id' => customer5.id, 'film_id' => film6.id, 'cinema' => 'Edinburgh', 'type' => 'full price')
ticket12.save()
ticket13 = Ticket.new('customer_id' => customer5.id, 'film_id' => film7.id, 'cinema' => 'Edinburgh', 'type' => 'full price')
ticket13.save()
ticket14 = Ticket.new('customer_id' => customer2.id, 'film_id' => film5.id, 'cinema' => 'Edinburgh', 'type' => 'full price')
ticket14.save()
ticket15 = Ticket.new('customer_id' => customer3.id, 'film_id' => film7.id, 'cinema' => 'Edinburgh', 'type' => 'peak')
ticket15.save()
ticket16 = Ticket.new('customer_id' => customer1.id, 'film_id' => film1.id, 'cinema' => 'Edinburgh', 'type' => 'discounted')
ticket16.save()
ticket17 = Ticket.new('customer_id' => customer1.id, 'film_id' => film1.id, 'cinema' => 'Edinburgh', 'type' => 'full price')
ticket17.save()

# ----------------------------------------

show1 = Screening.new('film_time' => '13:15', 'film_id' => film1.id)
show1.save()
show2 = Screening.new('film_time' => '20:15', 'film_id' => film1.id)
show2.save()
show3 = Screening.new('film_time' => '19:00', 'film_id' => film2.id)
show3.save()


binding.pry
nil